import "./js/menu";
import "./js/carousel";
import "./scss/styles.scss";
import "./static/img/image-big.png";
import "./static/img/image-big2.png";
import "./static/img/image-big3.jpg";
import "./static/img/phone.png";
import "./static/img/logo.png";
// alert('WorkFlow');
